# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wish_list', '0002_auto_20170324_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='added_by',
            field=models.CharField(default='Dalton', max_length=255),
            preserve_default=False,
        ),
    ]
