# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginregistration', '0001_initial'),
        ('wish_list', '0003_item_added_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='user',
        ),
        migrations.AddField(
            model_name='item',
            name='user',
            field=models.ManyToManyField(to='loginregistration.User'),
        ),
    ]
