# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wish_list', '0004_auto_20170324_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='user',
            field=models.ManyToManyField(related_name='items', to='loginregistration.User'),
        ),
    ]
